# Generated by Django 3.0.4 on 2020-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('hospital_currently', models.TextField(blank=True)),
                ('icu_currently', models.TextField(blank=True)),
                ('hospital_increase', models.TextField(blank=True)),
                ('dead_daily', models.TextField(blank=True)),
                ('tested_today', models.TextField(blank=True)),
            ],
        ),
    ]
