# Generated by Django 2.0.7 on 2020-05-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='icu_currently',
            new_name='ICU_currently',
        ),
    ]
