# Generated by Django 2.0.7 on 2020-05-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20200506_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='icu_currently',
            new_name='icucurrently',
        ),
    ]
