# Generated by Django 2.0.7 on 2020-05-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_auto_20200506_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='icucurrently',
            field=models.IntegerField(),
        ),
    ]
