# Generated by Django 2.0.7 on 2020-05-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_auto_20200506_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='dead_daily',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_increase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tested_today',
            field=models.IntegerField(),
        ),
    ]
